{% set name = "xtb" %}
{% set version = "6.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/xtb/releases/download/v{{ version }}/xtb-{{ version }}-source.tar.xz
  sha256: 5f780656bf7b440a8e1f753a9a877401a7d497fb3160762f48bdefc8a9914976

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('xtb', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - meson
    - ninja
    - asciidoctor
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libblas
    - liblapack
    - mctc-lib


test:
  commands:
    - xtb --version

about:
  home: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/xtb
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Semiempirical Extended Tight-Binding Program Package
  doc_url: https://xtb-docs.readthedocs.io/
  dev_url: https://github.com/grimme-lab/xtb

extra:
  recipe-maintainers:
    - awvwgk
